# Config for Application

# API Endpoints
[websocket]
endpoint = "wss://ws.cex.io/ws" #Endpoint

# Authorization Config for cex.io
[auth]
key    = "" # API_KEY
secret = "" #API_SECRET

# Logging Related Config
[log]
path = "."
filename = "marketdata.log"

# Market Data Publishing
[zmq]
publisher_ip=""
publisher_port=""

